/**
 * Static seed for the `devin-http` provider (direct Cascade HTTP).
 *
 * Generated from the live `GetCliModelConfigs` roster on 2026-09-12 (devin 3000.10.21, Free plan):
 * 209 roster uids folded to 74 selectable models. Live discovery is authoritative and this seed is
 * only the degraded fallback, so a stale entry here costs availability, never correctness.
 *
 * The fold is: base + orthogonal axes (`-fast`, `-priority`, `-lightning`, `-1m`, `-thinking`) is
 * the selectable id, and the reasoning-effort rung becomes that id's ladder. `DEVIN_HTTP_MODEL_WIRE_UIDS`
 * is the authoritative rung→uid map; the exposure rules live in `src/adapters/devin-http/roster.ts`.
 *
 * The `MODEL_*` entries are the account's legacy-convention models (Claude Sonnet 4.5, GPT-4.1,
 * Gemini 3 Flash, GPT-5.2 ...). They are real and callable, but their separators do not distinguish
 * base from rung, so they are carried unfolded rather than guessed at.
 */
export const DEVIN_HTTP_MODELS = [
  "claude-opus-5",
  "claude-fable-5-1",
  "claude-sonnet-5",
  "gemini-3-7-flash",
  "gemini-3-8-flash",
  "gpt-5-6-sol",
  "gpt-5-6-luna",
  "gpt-6-astra",
  "glm-5-2",
  "kimi-k3",
  "glm-5-3",
  "swe-1-7-lightning",
  "swe-2",
  "claude-opus-4-7",
  "claude-opus-4-8",
  "claude-opus-4-8-fast",
  "claude-opus-5-fast",
  "claude-5-fable",
  "gemini-3-5-flash",
  "gemini-3-6-flash",
  "gpt-5-6-sol-priority",
  "gpt-5-6-terra",
  "gpt-5-6-terra-priority",
  "gpt-5-6-luna-priority",
  "gpt-6-astra-priority",
  "glm-5-2-1m",
  "grok-4-5",
  "grok-4-6",
  "inkling",
  "glm-5-3-flash",
  "deepseek-v4-flash",
  "deepseek-v4-1-flash",
  "swe-1-7",
  "claude-opus-4-6",
  "claude-opus-4-6-thinking",
  "claude-opus-4-6-1m",
  "claude-opus-4-6-thinking-1m",
  "gpt-5-4",
  "gpt-5-5",
  "gpt-5-5-priority",
  "gpt-5-4-priority",
  "gpt-5-4-mini",
  "claude-sonnet-4-6",
  "claude-sonnet-4-6-thinking",
  "claude-sonnet-4-6-1m",
  "claude-sonnet-4-6-thinking-1m",
  "gpt-5-3-codex",
  "gpt-5-3-codex-priority",
  "kimi-k2-6",
  "kimi-k2-7",
  "nemotron-3-ultra",
  "swe-1-6",
  "swe-1-6-fast",
  "gemini-3-1-pro",
  "deepseek-v4-pro",
  "MODEL_GPT_5_2_LOW",
  "MODEL_GPT_5_2_MEDIUM",
  "MODEL_CLAUDE_4_5_OPUS",
  "MODEL_CLAUDE_4_5_OPUS_THINKING",
  "MODEL_PRIVATE_11",
  "MODEL_PRIVATE_2",
  "MODEL_PRIVATE_3",
  "MODEL_CHAT_GPT_4_1_2025_04_14",
  "MODEL_PRIVATE_12",
  "MODEL_PRIVATE_13",
  "MODEL_PRIVATE_14",
  "MODEL_PRIVATE_15",
  "MODEL_GPT_5_2_NONE",
  "MODEL_GPT_5_2_HIGH",
  "MODEL_GPT_5_2_XHIGH",
  "MODEL_GOOGLE_GEMINI_3_0_FLASH_MINIMAL",
  "MODEL_GOOGLE_GEMINI_3_0_FLASH_LOW",
  "MODEL_GOOGLE_GEMINI_3_0_FLASH_MEDIUM",
  "MODEL_GOOGLE_GEMINI_3_0_FLASH_HIGH",
] as const;

export const DEVIN_HTTP_MODEL_CONTEXT_WINDOWS: Record<string, number> = {
  "claude-opus-5": 1000000,
  "claude-fable-5-1": 1000000,
  "claude-sonnet-5": 1000000,
  "gemini-3-7-flash": 1048576,
  "gemini-3-8-flash": 1048576,
  "gpt-5-6-sol": 1000000,
  "gpt-5-6-luna": 1000000,
  "gpt-6-astra": 1000000,
  "glm-5-2": 200000,
  "kimi-k3": 1048576,
  "glm-5-3": 1048576,
  "swe-1-7-lightning": 202752,
  "swe-2": 262000,
  "claude-opus-4-7": 1000000,
  "claude-opus-4-8": 1000000,
  "claude-opus-4-8-fast": 1000000,
  "claude-opus-5-fast": 1000000,
  "claude-5-fable": 1000000,
  "gemini-3-5-flash": 1048576,
  "gemini-3-6-flash": 1048576,
  "gpt-5-6-sol-priority": 1000000,
  "gpt-5-6-terra": 1000000,
  "gpt-5-6-terra-priority": 1000000,
  "gpt-5-6-luna-priority": 1000000,
  "gpt-6-astra-priority": 1000000,
  "glm-5-2-1m": 1000000,
  "grok-4-5": 500000,
  "grok-4-6": 500000,
  "inkling": 1048576,
  "glm-5-3-flash": 1000000,
  "deepseek-v4-flash": 1048576,
  "deepseek-v4-1-flash": 1048576,
  "swe-1-7": 262000,
  "claude-opus-4-6": 200000,
  "claude-opus-4-6-thinking": 200000,
  "claude-opus-4-6-1m": 1000000,
  "claude-opus-4-6-thinking-1m": 1000000,
  "gpt-5-4": 272000,
  "gpt-5-5": 272000,
  "gpt-5-5-priority": 272000,
  "gpt-5-4-priority": 272000,
  "gpt-5-4-mini": 400000,
  "claude-sonnet-4-6": 200000,
  "claude-sonnet-4-6-thinking": 200000,
  "claude-sonnet-4-6-1m": 1000000,
  "claude-sonnet-4-6-thinking-1m": 1000000,
  "gpt-5-3-codex": 400000,
  "gpt-5-3-codex-priority": 400000,
  "kimi-k2-6": 262144,
  "kimi-k2-7": 262144,
  "nemotron-3-ultra": 1000000,
  "swe-1-6": 200000,
  "swe-1-6-fast": 200000,
  "gemini-3-1-pro": 1048576,
  "deepseek-v4-pro": 1048576,
  "MODEL_GPT_5_2_LOW": 384000,
  "MODEL_GPT_5_2_MEDIUM": 384000,
  "MODEL_CLAUDE_4_5_OPUS": 200000,
  "MODEL_CLAUDE_4_5_OPUS_THINKING": 200000,
  "MODEL_PRIVATE_11": 200000,
  "MODEL_PRIVATE_2": 200000,
  "MODEL_PRIVATE_3": 200000,
  "MODEL_CHAT_GPT_4_1_2025_04_14": 1047576,
  "MODEL_PRIVATE_12": 272000,
  "MODEL_PRIVATE_13": 272000,
  "MODEL_PRIVATE_14": 272000,
  "MODEL_PRIVATE_15": 272000,
  "MODEL_GPT_5_2_NONE": 384000,
  "MODEL_GPT_5_2_HIGH": 384000,
  "MODEL_GPT_5_2_XHIGH": 384000,
  "MODEL_GOOGLE_GEMINI_3_0_FLASH_MINIMAL": 1048576,
  "MODEL_GOOGLE_GEMINI_3_0_FLASH_LOW": 1048576,
  "MODEL_GOOGLE_GEMINI_3_0_FLASH_MEDIUM": 1048576,
  "MODEL_GOOGLE_GEMINI_3_0_FLASH_HIGH": 1048576,
};

export const DEVIN_HTTP_MODEL_REASONING_EFFORTS: Record<string, string[]> = {
  "claude-opus-5": ["medium", "low", "high", "xhigh", "max"],
  "claude-fable-5-1": ["medium", "low", "high", "xhigh", "max"],
  "claude-sonnet-5": ["medium", "low", "high", "xhigh", "max"],
  "gemini-3-7-flash": ["medium", "low", "high"],
  "gemini-3-8-flash": ["medium", "low", "high"],
  "gpt-5-6-sol": ["medium", "none", "low", "high", "xhigh", "max"],
  "gpt-5-6-luna": ["medium", "none", "low", "high", "xhigh", "max"],
  "gpt-6-astra": ["medium", "low", "high", "xhigh", "max"],
  "glm-5-2": ["max", "none"],
  "kimi-k3": ["high", "low", "max"],
  "glm-5-3": ["low", "high", "max"],
  "swe-1-7-lightning": ["medium"],
  "swe-2": ["high", "medium", "max"],
  "claude-opus-4-7": ["medium", "low", "high", "xhigh", "max"],
  "claude-opus-4-8": ["medium", "low", "high", "xhigh", "max"],
  "claude-opus-4-8-fast": ["low", "medium", "high", "xhigh", "max"],
  "claude-opus-5-fast": ["low", "medium", "high", "xhigh", "max"],
  "claude-5-fable": ["low", "medium", "high", "xhigh", "max"],
  "gemini-3-5-flash": ["minimal", "low", "medium", "high"],
  "gemini-3-6-flash": ["minimal", "low", "medium", "high"],
  "gpt-5-6-sol-priority": ["none", "low", "medium", "high", "xhigh", "max"],
  "gpt-5-6-terra": ["none", "low", "medium", "high", "xhigh", "max"],
  "gpt-5-6-terra-priority": ["none", "low", "medium", "high", "xhigh", "max"],
  "gpt-5-6-luna-priority": ["none", "low", "medium", "high", "xhigh", "max"],
  "gpt-6-astra-priority": ["low", "medium", "high", "xhigh", "max"],
  "glm-5-2-1m": ["max", "none"],
  "grok-4-5": ["low", "medium", "high"],
  "grok-4-6": ["low", "medium", "high", "xhigh"],
  "inkling": ["none", "low", "medium", "high", "xhigh", "max"],
  "glm-5-3-flash": ["low", "high", "max"],
  "deepseek-v4-flash": ["high", "max"],
  "deepseek-v4-1-flash": ["high", "max"],
  "swe-1-7": ["medium"],
  "gpt-5-4": ["none", "low", "medium", "high", "xhigh"],
  "gpt-5-5": ["none", "low", "medium", "high", "xhigh"],
  "gpt-5-5-priority": ["none", "low", "medium", "high", "xhigh"],
  "gpt-5-4-priority": ["none", "low", "medium", "high", "xhigh"],
  "gpt-5-4-mini": ["low", "medium", "high", "xhigh"],
  "gpt-5-3-codex": ["low", "medium", "high", "xhigh"],
  "gpt-5-3-codex-priority": ["low", "medium", "high", "xhigh"],
  "nemotron-3-ultra": ["none", "medium", "high"],
  "gemini-3-1-pro": ["low", "high"],
  "deepseek-v4-pro": ["high", "max"],
};

export const DEVIN_HTTP_MODEL_DEFAULT_REASONING_EFFORTS: Record<string, string> = {
  "claude-opus-5": "medium",
  "claude-fable-5-1": "medium",
  "claude-sonnet-5": "medium",
  "gemini-3-7-flash": "medium",
  "gemini-3-8-flash": "medium",
  "gpt-5-6-sol": "medium",
  "gpt-5-6-luna": "medium",
  "gpt-6-astra": "medium",
  "kimi-k3": "high",
  "glm-5-3": "low",
  "swe-2": "high",
  "claude-opus-4-7": "medium",
  "claude-opus-4-8": "medium",
  "claude-opus-4-8-fast": "low",
  "claude-opus-5-fast": "low",
  "claude-5-fable": "low",
  "gemini-3-5-flash": "minimal",
  "gemini-3-6-flash": "minimal",
  "gpt-5-6-sol-priority": "none",
  "gpt-5-6-terra": "none",
  "gpt-5-6-terra-priority": "none",
  "gpt-5-6-luna-priority": "none",
  "gpt-6-astra-priority": "low",
  "grok-4-5": "low",
  "grok-4-6": "low",
  "inkling": "none",
  "glm-5-3-flash": "low",
  "deepseek-v4-flash": "high",
  "deepseek-v4-1-flash": "high",
  "gpt-5-4": "none",
  "gpt-5-5": "none",
  "gpt-5-5-priority": "none",
  "gpt-5-4-priority": "none",
  "gpt-5-4-mini": "low",
  "gpt-5-3-codex": "low",
  "gpt-5-3-codex-priority": "low",
  "nemotron-3-ultra": "none",
  "gemini-3-1-pro": "low",
  "deepseek-v4-pro": "high",
};

/** Exact roster uid per rung. Never reconstructed: the rung order is not uniform. */
export const DEVIN_HTTP_MODEL_WIRE_UIDS: Record<string, Record<string, string>> = {
  "claude-opus-5": { "medium": "claude-opus-5-medium", "low": "claude-opus-5-low", "high": "claude-opus-5-high", "xhigh": "claude-opus-5-xhigh", "max": "claude-opus-5-max" },
  "claude-fable-5-1": { "medium": "claude-fable-5-1-medium", "low": "claude-fable-5-1-low", "high": "claude-fable-5-1-high", "xhigh": "claude-fable-5-1-xhigh", "max": "claude-fable-5-1-max" },
  "claude-sonnet-5": { "medium": "claude-sonnet-5-medium", "low": "claude-sonnet-5-low", "high": "claude-sonnet-5-high", "xhigh": "claude-sonnet-5-xhigh", "max": "claude-sonnet-5-max" },
  "gemini-3-7-flash": { "medium": "gemini-3-7-flash-medium", "low": "gemini-3-7-flash-low", "high": "gemini-3-7-flash-high" },
  "gemini-3-8-flash": { "medium": "gemini-3-8-flash-medium", "low": "gemini-3-8-flash-low", "high": "gemini-3-8-flash-high" },
  "gpt-5-6-sol": { "medium": "gpt-5-6-sol-medium", "none": "gpt-5-6-sol-none", "low": "gpt-5-6-sol-low", "high": "gpt-5-6-sol-high", "xhigh": "gpt-5-6-sol-xhigh", "max": "gpt-5-6-sol-max" },
  "gpt-5-6-luna": { "medium": "gpt-5-6-luna-medium", "none": "gpt-5-6-luna-none", "low": "gpt-5-6-luna-low", "high": "gpt-5-6-luna-high", "xhigh": "gpt-5-6-luna-xhigh", "max": "gpt-5-6-luna-max" },
  "gpt-6-astra": { "medium": "gpt-6-astra-medium", "low": "gpt-6-astra-low", "high": "gpt-6-astra-high", "xhigh": "gpt-6-astra-xhigh", "max": "gpt-6-astra-max" },
  "glm-5-2": { "": "glm-5-2", "max": "glm-5-2-max", "none": "glm-5-2-none" },
  "kimi-k3": { "high": "kimi-k3-high", "low": "kimi-k3-low", "max": "kimi-k3-max" },
  "glm-5-3": { "low": "glm-5-3-low", "high": "glm-5-3-high", "max": "glm-5-3-max" },
  "swe-1-7-lightning": { "": "swe-1-7-lightning", "medium": "swe-1-7-lightning-medium" },
  "swe-2": { "high": "swe-2-high", "medium": "swe-2-medium", "max": "swe-2-max" },
  "claude-opus-4-7": { "medium": "claude-opus-4-7-medium", "low": "claude-opus-4-7-low", "high": "claude-opus-4-7-high", "xhigh": "claude-opus-4-7-xhigh", "max": "claude-opus-4-7-max" },
  "claude-opus-4-8": { "medium": "claude-opus-4-8-medium", "low": "claude-opus-4-8-low", "high": "claude-opus-4-8-high", "xhigh": "claude-opus-4-8-xhigh", "max": "claude-opus-4-8-max" },
  "claude-opus-4-8-fast": { "low": "claude-opus-4-8-low-fast", "medium": "claude-opus-4-8-medium-fast", "high": "claude-opus-4-8-high-fast", "xhigh": "claude-opus-4-8-xhigh-fast", "max": "claude-opus-4-8-max-fast" },
  "claude-opus-5-fast": { "low": "claude-opus-5-low-fast", "medium": "claude-opus-5-medium-fast", "high": "claude-opus-5-high-fast", "xhigh": "claude-opus-5-xhigh-fast", "max": "claude-opus-5-max-fast" },
  "claude-5-fable": { "low": "claude-5-fable-low", "medium": "claude-5-fable-medium", "high": "claude-5-fable-high", "xhigh": "claude-5-fable-xhigh", "max": "claude-5-fable-max" },
  "gemini-3-5-flash": { "minimal": "gemini-3-5-flash-minimal", "low": "gemini-3-5-flash-low", "medium": "gemini-3-5-flash-medium", "high": "gemini-3-5-flash-high" },
  "gemini-3-6-flash": { "minimal": "gemini-3-6-flash-minimal", "low": "gemini-3-6-flash-low", "medium": "gemini-3-6-flash-medium", "high": "gemini-3-6-flash-high" },
  "gpt-5-6-sol-priority": { "none": "gpt-5-6-sol-none-priority", "low": "gpt-5-6-sol-low-priority", "medium": "gpt-5-6-sol-medium-priority", "high": "gpt-5-6-sol-high-priority", "xhigh": "gpt-5-6-sol-xhigh-priority", "max": "gpt-5-6-sol-max-priority" },
  "gpt-5-6-terra": { "none": "gpt-5-6-terra-none", "low": "gpt-5-6-terra-low", "medium": "gpt-5-6-terra-medium", "high": "gpt-5-6-terra-high", "xhigh": "gpt-5-6-terra-xhigh", "max": "gpt-5-6-terra-max" },
  "gpt-5-6-terra-priority": { "none": "gpt-5-6-terra-none-priority", "low": "gpt-5-6-terra-low-priority", "medium": "gpt-5-6-terra-medium-priority", "high": "gpt-5-6-terra-high-priority", "xhigh": "gpt-5-6-terra-xhigh-priority", "max": "gpt-5-6-terra-max-priority" },
  "gpt-5-6-luna-priority": { "none": "gpt-5-6-luna-none-priority", "low": "gpt-5-6-luna-low-priority", "medium": "gpt-5-6-luna-medium-priority", "high": "gpt-5-6-luna-high-priority", "xhigh": "gpt-5-6-luna-xhigh-priority", "max": "gpt-5-6-luna-max-priority" },
  "gpt-6-astra-priority": { "low": "gpt-6-astra-low-priority", "medium": "gpt-6-astra-medium-priority", "high": "gpt-6-astra-high-priority", "xhigh": "gpt-6-astra-xhigh-priority", "max": "gpt-6-astra-max-priority" },
  "glm-5-2-1m": { "": "glm-5-2-1m", "max": "glm-5-2-max-1m", "none": "glm-5-2-none-1m" },
  "grok-4-5": { "low": "grok-4-5-low", "medium": "grok-4-5-medium", "high": "grok-4-5-high" },
  "grok-4-6": { "low": "grok-4-6-low", "medium": "grok-4-6-medium", "high": "grok-4-6-high", "xhigh": "grok-4-6-xhigh" },
  "inkling": { "none": "inkling-none", "low": "inkling-low", "medium": "inkling-medium", "high": "inkling-high", "xhigh": "inkling-xhigh", "max": "inkling-max" },
  "glm-5-3-flash": { "low": "glm-5-3-flash-low", "high": "glm-5-3-flash-high", "max": "glm-5-3-flash-max" },
  "deepseek-v4-flash": { "high": "deepseek-v4-flash-high", "max": "deepseek-v4-flash-max" },
  "deepseek-v4-1-flash": { "high": "deepseek-v4-1-flash-high", "max": "deepseek-v4-1-flash-max" },
  "swe-1-7": { "": "swe-1-7", "medium": "swe-1-7-medium" },
  "claude-opus-4-6": { "": "claude-opus-4-6" },
  "claude-opus-4-6-thinking": { "": "claude-opus-4-6-thinking" },
  "claude-opus-4-6-1m": { "": "claude-opus-4-6-1m" },
  "claude-opus-4-6-thinking-1m": { "": "claude-opus-4-6-thinking-1m" },
  "gpt-5-4": { "none": "gpt-5-4-none", "low": "gpt-5-4-low", "medium": "gpt-5-4-medium", "high": "gpt-5-4-high", "xhigh": "gpt-5-4-xhigh" },
  "gpt-5-5": { "none": "gpt-5-5-none", "low": "gpt-5-5-low", "medium": "gpt-5-5-medium", "high": "gpt-5-5-high", "xhigh": "gpt-5-5-xhigh" },
  "gpt-5-5-priority": { "none": "gpt-5-5-none-priority", "low": "gpt-5-5-low-priority", "medium": "gpt-5-5-medium-priority", "high": "gpt-5-5-high-priority", "xhigh": "gpt-5-5-xhigh-priority" },
  "gpt-5-4-priority": { "none": "gpt-5-4-none-priority", "low": "gpt-5-4-low-priority", "medium": "gpt-5-4-medium-priority", "high": "gpt-5-4-high-priority", "xhigh": "gpt-5-4-xhigh-priority" },
  "gpt-5-4-mini": { "low": "gpt-5-4-mini-low", "medium": "gpt-5-4-mini-medium", "high": "gpt-5-4-mini-high", "xhigh": "gpt-5-4-mini-xhigh" },
  "claude-sonnet-4-6": { "": "claude-sonnet-4-6" },
  "claude-sonnet-4-6-thinking": { "": "claude-sonnet-4-6-thinking" },
  "claude-sonnet-4-6-1m": { "": "claude-sonnet-4-6-1m" },
  "claude-sonnet-4-6-thinking-1m": { "": "claude-sonnet-4-6-thinking-1m" },
  "gpt-5-3-codex": { "low": "gpt-5-3-codex-low", "medium": "gpt-5-3-codex-medium", "high": "gpt-5-3-codex-high", "xhigh": "gpt-5-3-codex-xhigh" },
  "gpt-5-3-codex-priority": { "low": "gpt-5-3-codex-low-priority", "medium": "gpt-5-3-codex-medium-priority", "high": "gpt-5-3-codex-high-priority", "xhigh": "gpt-5-3-codex-xhigh-priority" },
  "kimi-k2-6": { "": "kimi-k2-6" },
  "kimi-k2-7": { "": "kimi-k2-7" },
  "nemotron-3-ultra": { "none": "nemotron-3-ultra-none", "medium": "nemotron-3-ultra-medium", "high": "nemotron-3-ultra-high" },
  "swe-1-6": { "": "swe-1-6" },
  "swe-1-6-fast": { "": "swe-1-6-fast" },
  "gemini-3-1-pro": { "low": "gemini-3-1-pro-low", "high": "gemini-3-1-pro-high" },
  "deepseek-v4-pro": { "high": "deepseek-v4-pro-high", "max": "deepseek-v4-pro-max" },
  "MODEL_GPT_5_2_LOW": { "": "MODEL_GPT_5_2_LOW" },
  "MODEL_GPT_5_2_MEDIUM": { "": "MODEL_GPT_5_2_MEDIUM" },
  "MODEL_CLAUDE_4_5_OPUS": { "": "MODEL_CLAUDE_4_5_OPUS" },
  "MODEL_CLAUDE_4_5_OPUS_THINKING": { "": "MODEL_CLAUDE_4_5_OPUS_THINKING" },
  "MODEL_PRIVATE_11": { "": "MODEL_PRIVATE_11" },
  "MODEL_PRIVATE_2": { "": "MODEL_PRIVATE_2" },
  "MODEL_PRIVATE_3": { "": "MODEL_PRIVATE_3" },
  "MODEL_CHAT_GPT_4_1_2025_04_14": { "": "MODEL_CHAT_GPT_4_1_2025_04_14" },
  "MODEL_PRIVATE_12": { "": "MODEL_PRIVATE_12" },
  "MODEL_PRIVATE_13": { "": "MODEL_PRIVATE_13" },
  "MODEL_PRIVATE_14": { "": "MODEL_PRIVATE_14" },
  "MODEL_PRIVATE_15": { "": "MODEL_PRIVATE_15" },
  "MODEL_GPT_5_2_NONE": { "": "MODEL_GPT_5_2_NONE" },
  "MODEL_GPT_5_2_HIGH": { "": "MODEL_GPT_5_2_HIGH" },
  "MODEL_GPT_5_2_XHIGH": { "": "MODEL_GPT_5_2_XHIGH" },
  "MODEL_GOOGLE_GEMINI_3_0_FLASH_MINIMAL": { "": "MODEL_GOOGLE_GEMINI_3_0_FLASH_MINIMAL" },
  "MODEL_GOOGLE_GEMINI_3_0_FLASH_LOW": { "": "MODEL_GOOGLE_GEMINI_3_0_FLASH_LOW" },
  "MODEL_GOOGLE_GEMINI_3_0_FLASH_MEDIUM": { "": "MODEL_GOOGLE_GEMINI_3_0_FLASH_MEDIUM" },
  "MODEL_GOOGLE_GEMINI_3_0_FLASH_HIGH": { "": "MODEL_GOOGLE_GEMINI_3_0_FLASH_HIGH" },
};


/**
 * Input modalities per model, from the roster's per-variant `supports_images` flag.
 *
 * 67 of 74 accept images; the GLM and Inkling families are text-only. Publishing this keeps
 * the catalog honest — Codex gates attachments client-side, so a text-only model advertised as
 * multimodal would fail at request time instead of declining the attachment up front.
 */
export const DEVIN_HTTP_MODEL_INPUT_MODALITIES: Record<string, string[]> = {
  "claude-opus-5": ["text", "image"],
  "claude-fable-5-1": ["text", "image"],
  "claude-sonnet-5": ["text", "image"],
  "gemini-3-7-flash": ["text", "image"],
  "gemini-3-8-flash": ["text", "image"],
  "gpt-5-6-sol": ["text", "image"],
  "gpt-5-6-luna": ["text", "image"],
  "gpt-6-astra": ["text", "image"],
  "glm-5-2": ["text"],
  "kimi-k3": ["text", "image"],
  "glm-5-3": ["text"],
  "swe-1-7-lightning": ["text", "image"],
  "swe-2": ["text", "image"],
  "claude-opus-4-7": ["text", "image"],
  "claude-opus-4-8": ["text", "image"],
  "claude-opus-4-8-fast": ["text", "image"],
  "claude-opus-5-fast": ["text", "image"],
  "claude-5-fable": ["text", "image"],
  "gemini-3-5-flash": ["text", "image"],
  "gemini-3-6-flash": ["text", "image"],
  "gpt-5-6-sol-priority": ["text", "image"],
  "gpt-5-6-terra": ["text", "image"],
  "gpt-5-6-terra-priority": ["text", "image"],
  "gpt-5-6-luna-priority": ["text", "image"],
  "gpt-6-astra-priority": ["text", "image"],
  "glm-5-2-1m": ["text"],
  "grok-4-5": ["text", "image"],
  "grok-4-6": ["text", "image"],
  "inkling": ["text"],
  "glm-5-3-flash": ["text", "image"],
  "deepseek-v4-flash": ["text"],
  "deepseek-v4-1-flash": ["text", "image"],
  "swe-1-7": ["text", "image"],
  "claude-opus-4-6": ["text", "image"],
  "claude-opus-4-6-thinking": ["text", "image"],
  "claude-opus-4-6-1m": ["text", "image"],
  "claude-opus-4-6-thinking-1m": ["text", "image"],
  "gpt-5-4": ["text", "image"],
  "gpt-5-5": ["text", "image"],
  "gpt-5-5-priority": ["text", "image"],
  "gpt-5-4-priority": ["text", "image"],
  "gpt-5-4-mini": ["text", "image"],
  "claude-sonnet-4-6": ["text", "image"],
  "claude-sonnet-4-6-thinking": ["text", "image"],
  "claude-sonnet-4-6-1m": ["text", "image"],
  "claude-sonnet-4-6-thinking-1m": ["text", "image"],
  "gpt-5-3-codex": ["text", "image"],
  "gpt-5-3-codex-priority": ["text", "image"],
  "kimi-k2-6": ["text", "image"],
  "kimi-k2-7": ["text", "image"],
  "nemotron-3-ultra": ["text"],
  "swe-1-6": ["text", "image"],
  "swe-1-6-fast": ["text", "image"],
  "gemini-3-1-pro": ["text", "image"],
  "deepseek-v4-pro": ["text"],
  "MODEL_GPT_5_2_LOW": ["text", "image"],
  "MODEL_GPT_5_2_MEDIUM": ["text", "image"],
  "MODEL_CLAUDE_4_5_OPUS": ["text", "image"],
  "MODEL_CLAUDE_4_5_OPUS_THINKING": ["text", "image"],
  "MODEL_PRIVATE_11": ["text", "image"],
  "MODEL_PRIVATE_2": ["text", "image"],
  "MODEL_PRIVATE_3": ["text", "image"],
  "MODEL_CHAT_GPT_4_1_2025_04_14": ["text", "image"],
  "MODEL_PRIVATE_12": ["text", "image"],
  "MODEL_PRIVATE_13": ["text", "image"],
  "MODEL_PRIVATE_14": ["text", "image"],
  "MODEL_PRIVATE_15": ["text", "image"],
  "MODEL_GPT_5_2_NONE": ["text", "image"],
  "MODEL_GPT_5_2_HIGH": ["text", "image"],
  "MODEL_GPT_5_2_XHIGH": ["text", "image"],
  "MODEL_GOOGLE_GEMINI_3_0_FLASH_MINIMAL": ["text", "image"],
  "MODEL_GOOGLE_GEMINI_3_0_FLASH_LOW": ["text", "image"],
  "MODEL_GOOGLE_GEMINI_3_0_FLASH_MEDIUM": ["text", "image"],
  "MODEL_GOOGLE_GEMINI_3_0_FLASH_HIGH": ["text", "image"],
};
